project:
  type: website
  output-dir: _site
  
website:
  title: "Subina Shakya"

  description: "Some description"
  site-url: su-shakya.github.io
  repo-url: https://github.com/su-shakya/su-shakya.github.io/
  favicon: assets/images/ss_headshot.jpg
  image: assets/images/ss_headshot.jpg
  open-graph: true
  search: true
  # reader-mode: true
  navbar:
    title: "Subina Shakya"
    # logo: assets/images/ss_headshot.jpg
    # logo-alt: "Professional Headshot Photo"
    # logo-href: https://su-shakya.github.io/
    collapse: true
    
    left:
      - href: content/about.qmd
        text: "About" # Menu title of document, automatically from document title if not provided
      - href: content/resume.qmd
        text: "Resume" # Menu title of document, automatically from document title if not provided

    # add sections here
      # - href: content/subpage.qmd
      #   text: "Subpage_Title"
      
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/subinashakya/
      - icon: github
        href: https://github.com/su-shakya
      - icon: envelope-fill
        href: mailto::subina.shakya@colostate.edu

  page-footer:
    border: false
    left: © 2025 [Subina Shakya](https://su-shakya.github.io)
    center: |
          <a href="https://www.linkedin.com/in/subinashakya" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
          &nbsp;
          <a href="https://github.com/su-shakya/" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
          &nbsp;
          <a href="mailto:subina.shakya@colostate.edu" title="E-mail" target="_blank" rel="noopener">{{< fa envelope >}}</a>
    right: Made with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, [<img src="https://quarto.org/favicon.png" width="14">](https://quarto.org/){target=_blank}, [{{< fa brands git-alt title="Git alt logo" >}}](https://git-scm.com/){target=_blank} and [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/){target=_blank}

format:
  html: # (https://quarto.org/docs/reference/formats/html.html)
    respect-user-color-scheme: true
    theme: 
      light: assets/theme/ss-theme-light.scss
      dark: assets/theme/ss-theme-dark.scss
    css: assets/theme/ss-styles.css

    highlight: arrow
    highlight-style: 
      light: assets/theme/ss-light.theme
      dark: assets/theme/ss-dark.theme
    
    mainfont: Poppins
    monofont: "Fira Code"
    toc: false
    smooth-scroll: true
    page-layout: article
    code-copy: hover
    code-overflow: wrap
    code-line-numbers: false
    code-block-border-left: true
    freeze: auto
    # grid:
    #   sidebar-width: 250px
    #   body-width: 1200px
    #   margin-width: 250px

tbl-cap-location: top

# bibliography: ../references.bib


